### Registration
POST localhost:8080/auth/registration
Content-Type: application/json

{
  "name": "shakh",
  "surname": "islamov",
  "email": "shohruxjan8892@gmail.com",
  "password": "4444",
  "phone": "+998975492400"
}


### Verification
GET localhost:8080/auth/verification/5

### Login
POST localhost:8080/auth/login
Content-Type: application/json

{
  "email": "shohruxjan8892@gmail.com",
  "password": "4444"
}

### Resend
GET localhost:8080/auth/registration/resend/j22@gmail.com
